# Generated by Django 5.1.5 on 2025-03-26 16:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='password',
            options={'verbose_name': 'Password', 'verbose_name_plural': 'Passwords'},
        ),
        migrations.AlterUniqueTogether(
            name='password',
            unique_together={('user', 'website')},
        ),
    ]
